DEBUG:root:Holaaaaaaa
ERROR:app:Exception on /buscarUsuario [POST]
Traceback (most recent call last):
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ecpadmin/MyEcoApps/app.py", line 154, in buscarUsuario
    'ROL': usuario.id,
AttributeError: 'NoneType' object has no attribute 'id'
DEBUG:root:Holaaaaaaa
ERROR:app:Exception on /buscarUsuario [POST]
Traceback (most recent call last):
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ecpadmin/MyEcoApps/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ecpadmin/MyEcoApps/app.py", line 154, in buscarUsuario
    'ROL': usuario.id,
AttributeError: 'NoneType' object has no attribute 'id'
